name: Url Health Check Action

on:
  schedule:
    - cron:  20/15 * * * *

jobs: 
  simple-deployment-pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://arcane-wave-85428.herokuapp.com/