name: Simple deployment pipeline

on:
  push:
    branches:
      - master

jobs: 
  simple-deployment-pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build 
      - name: test
        run: npm run test
      - name: heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "arcane-wave-85428"
          heroku_email: "elsi.silvennoinen@gmail.com"
          healthcheck: "https://arcane-wave-85428.herokuapp.com/health"
          checkstring: "ok"